server:
  port: 9090
spring:
  data:
    mongodb:
      primary:
        host: jx.51wbar.com
        port: 27017
        database: yunchong
        password: mongo_db
        username: mongo_db
        authentication-database: admin
      second:
        host: jx.51wbar.com
        port: 27017
        database: gps_mongodb
        password: mongo_db
        username: mongo_db
        authentication-database: admin
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://test.jxnewlife.com:13306/newlife_s4?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: newlife_s4
      password: newlife_s4
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 3
      minIdle: 10
      maxIdle: 10
      maxActive: 20
      maxWait: 10000
      keepAlive: true
      removeAbandoned: true
      removeAbandonedTimeout: 80
      logAbandoned: true
  redis:
     # Redis服务器地址
      host: sit.jxnewlife.com
      # Redis服务器连接端口
      port: 16379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间（毫秒）
      timeout: 6000
      # 连接指定的数据库
      database: 9
       # 连接池最大连接数（使用负值表示没有限制）
      pool:
         max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1
        # 连接池中的最大空闲连接
         max-idle: 8
        # 连接池中的最小空闲连接
         min-idle: 0

#微信配置
wx:
  #公众号 APP_ID
  appId: wx85585e7d94fe22be
  #公众号 APP_SECRET
  appSecret: 343c5d78b2ccdcc02d2f26a70a181236
  #公众号 TOKEN
  token: chiv88
  #公众号 AES_KEY
  aesKey: X1vk8xP2RDM7uGf9paEGXmqr4hfHprJeHoZzb2kGylc
  #商户号
  mchId: 1508509831
  #微信支付平台商户API密钥
  mchKey: 45adsfSDFERdKKUY1123345fdfddKYDS
  #服务商模式下的子商户公众账号ID
  subAppId:
  #服务商模式下的子商户号
  subMchId:
  #apiclient_cert.p12 证书文件的绝对路径
  keyPath: "/data/newlife/newlife_s4_api/cert.zip"
  #支付回调地址
  notifyUrl: "http://wx.jxnewlife.com/api/wechat/payOrder4m"
  #微信登陆后跳转地址
  redirectDomain: "http://test.jxnewlife.com/"
  #微信登陆后跳转地址
  apiDomain: "http://test.jxnewlife.com/api"

#存储服务器配置
storageService:
  #文件存储服务器地址 "http://192.168.2.51:8080/" "http://www.jxnewlife.com:9092/"
  fileStorageAddress: "http://192.168.1.252:9092/"
  
#swagger-ui接口地址配置
swagger:
  host: "test.jxnewlife.com"

##文件上传绝对路径
jetty:
   path: "/data/newlife/newlife_s4_weex_resources"

GPS:
  aesKey: newlife
  notifyUrl : "http://192.168.1.252:8000/"
